
version: '2'
services:
  servlets:
    build: .
    volumes:
      - builds:/maven_build/
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - msnet
    restart: always
networks:
   msnet:
     driver: bridge
volumes:
  builds: {}
